//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TableId { get; set; }
        public int PeopleNo { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public string Status { get; set; }
    
        public virtual Tables Tables { get; set; }
        public virtual Users Users { get; set; }
    }
}
