//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestPro.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class reviews
    {
        public int Id { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RestID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        public virtual Users Users { get; set; }
    }
}
